---
title: "Road crash SA data"
author: "Asheshwor Man Shrestha"
date: "July 27, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploring road crash data

Source: https://data.sa.gov.au/data/dataset/road-crashes-in-sa

License: Creative Commons Attribution 3.0 Australia (CC BY 3.0 AU) license available here: http://creativecommons.org/licenses/by/3.0/au/

```{r load_libraries}
library(maptools)
library(rgdal)
library(rgeos)
require(dplyr)
require(leaflet)
```

```{r read_crash_data}
P4S.latlon <- CRS("+proj=longlat +datum=WGS84")
crashpoints <- readShapePoints("C:/Users/Lenovo/Documents/GitHub/crash/RoadCrashes_shp/RoadCrashes.shp",
                               verbose = TRUE,
                               proj4string = CRS("+init=epsg:3107"))
co <- coordinates(crashpoints)
# crashpoints3 <- readShapePoints("C:/Users/Lenovo/Documents/GitHub/crash/RoadCrashes_shp/RoadCrashes.shp", proj4string = CRS("+proj=longlat +datum=WGS84"))
# plot(crashpoints3)
plot(crashpoints)
str(crashpoints)
# 
# # Pull some observations and transform to Lat/Long
# meuse.geo <- meuse[sample(dim(meuse)[1],10),]
#   prj.LatLong <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")
#     meuse.geo <- spTransform(meuse.geo, prj.LatLong)
# 
# # Pull projection string from meuse.geo and use in spTransform
# #   to reproject meuse to lat/long  
# ( prj <- proj4string(meuse.geo) )   
# meuse <- spTransform(meuse, CRS(prj))   
crashpoints.t <- spTransform(crashpoints, CRS("+proj=longlat +datum=WGS84")) 
co.t <- data.frame(coordinates(crashpoints.t))
names(co.t) <- c("lon", "lat")
crashpoints.df <- cbind(data.frame(crashpoints), co.t)
write.csv(crashpoints.df, "crashpoints")
```

## Add to leaflet

```{r add_to_leaflet}
crashmap <- leaflet(data=co.t[sample(1:nrow(co.t), 1000), ]) %>%
  addProviderTiles('Stamen.TonerLite') %>%
      setView(138.592609, -34.912760,  zoom = 7) %>%
      addMarkers(~lon, ~lat, clusterOptions = markerClusterOptions()) %>%
      addLegend(
        "bottomleft", pal = pallet,
        values = sort(quake.get$size),
        title = "Magnitude"
        # labFormat = labelFormat()
      )
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
